Repository EXXETA/trufos, pull requests merged in 2024-12, with the labels that each got.

#159 fix(152): Adjust Sidebar Item Widths to match Figma Design
  docs/Screenshot-Request.png
  docs/Screenshot-nothing-selected.png
  src/renderer/components/sidebar/FooterBar.tsx
  src/renderer/components/sidebar/SidebarRequestList/index.tsx
  src/renderer/view/Sidebar.tsx
Labels: bug, frontend

#168 #167 - skip CI if PR is draft
  .github/workflows/ci.yml
  .github/workflows/pr.yml
Labels: setup

#170 #161 - Add Hotkey support(ctrl + s/cmd + s) to save opened requests.
  src/renderer/components/mainWindow/MainTopBar.tsx
Labels: enhancement, frontend

#164 feat(163): Add Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, setup
