Repository EXXETA/trufos, pull requests merged in 2025-01, with the labels that each got.

#166 feat(160): Variable Syntax Highlighting and Completion
  __tests__/monaco-util.ts
  jest.config.js
  src/main/environment/service/environment-service.ts
  src/main/environment/service/system-variable.test.ts
  src/main/environment/service/system-variable.ts
  src/main/event/main-event-service.ts
  src/main/import/service/postman-importer.ts
  src/main/persistence/service/default-collection.ts
  src/main/persistence/service/info-files.ts
  src/main/persistence/service/persistence-service.ts
  src/renderer/components/mainWindow/bodyTabs/InputTabs/index.tsx
  src/renderer/components/mainWindow/bodyTabs/OutputTabs.tsx
  src/renderer/components/shared/settings/monaco-settings.ts
  src/renderer/index.tsx
  src/renderer/lib/monaco/editor.d.ts
  src/renderer/lib/monaco/language.ts
  src/renderer/lib/monaco/template-variable-completion-items-provider.test.ts
  src/renderer/lib/monaco/template-variable-completion-items-provider.ts
  src/renderer/lib/monaco/template-variable-hover-provider.ts
  src/renderer/lib/monaco/template-variable-semantic-tokens-provider.test.ts
  src/renderer/lib/monaco/template-variable-semantic-tokens-provider.ts
  src/renderer/lib/monaco/token.ts
  src/renderer/services/event/renderer-event-service.ts
  src/shim/event-service.ts
  src/shim/objects/collection.ts
  src/shim/variables.ts
Labels: enhancement, frontend, backend

#198 fix(197): Installation Guide
  README.md
Labels: documentation, setup

#186 #182 - fixed url input field color according to figma
  src/renderer/components/mainWindow/mainTopBar/UrlInput.tsx
Labels: enhancement, frontend
