Repository EXXETA/trufos, pull requests merged in 2025-05, with the labels that each got.

#366 feat(114): Add Release Pipeline
  .github/workflows/release.yml
  .nvmrc
  forge.config.ts
  package.json
  src/main/logging/logger.test.ts
  yarn.lock
Labels: setup

#369 fix(336): Set draft state when modifying request headers
  src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/HeaderTab.tsx
Labels: frontend

#371 feat(205): Responsive layout for main body items based on screen size
  src/renderer/components/mainWindow/MainBody.tsx
  src/renderer/components/mainWindow/bodyTabs/OutputTabs.tsx
  src/renderer/view/RequestWindow.tsx
Labels: enhancement, frontend

#377 feat: Add Discord Banner to README
  README.md
Labels: enhancement, setup

#382 feat(65) - Add drag and drop zone for a request body file
  src/main/preload.ts
  src/renderer/components/mainWindow/MainBody.tsx
  src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/BodyTab.tsx
  src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/BodyTabFileInput.tsx
  src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/BodyTabTextInput.tsx
  src/renderer/components/mainWindow/bodyTabs/OutputTabs.tsx
  src/renderer/view/RequestWindow.tsx
  src/shim/objects/request.ts
Labels: enhancement, frontend
