Repository EXXETA/trufos, pull requests merged in 2025-02, with the labels that each got.

#224 fix(217): Create Dependabot Group for @typescript-eslint
  .github/dependabot.yml
Labels: dependencies

#238 fix(222): Monaco Errors in Frontend Console
  src/renderer/index.tsx
  src/renderer/lib/monaco/config.js
  src/renderer/lib/monaco/language.ts
  src/renderer/lib/monaco/template-variable-completion-items-provider.test.ts
  src/renderer/lib/monaco/template-variable-semantic-tokens-provider.test.ts
Labels: frontend

#270 add config for osxSign, osxNotarize
  forge.config.ts
Labels: setup

#265 #263 - Implement folder management functionality with add and delete options
  src/main/event/main-event-service.ts
  src/renderer/components/sidebar/SidebarHeaderBar.tsx
  src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/FolderDropdown.tsx
  src/renderer/services/event/renderer-event-service.ts
  src/renderer/state/collectionStore.ts
  src/renderer/state/interface/CollectionStateActions.ts
  src/shim/event-service.ts
Labels: enhancement, frontend

#268 feat(#206): Support switching and creating Collections
  src/main/environment/service/environment-service.test.ts
  src/main/environment/service/environment-service.ts
  src/main/event/main-event-service.ts
  src/main/main.ts
  src/main/persistence/service/default-collection.ts
  src/main/persistence/service/info-files/latest.ts
  src/main/persistence/service/persistence-service.test.ts
  src/main/persistence/service/persistence-service.ts
  src/main/persistence/service/settings-service.test.ts
  src/main/persistence/service/settings-service.ts
  src/renderer/services/event/renderer-event-service.ts
  src/shim/event-service.ts
Labels: enhancement, backend
